
name: Test & Deploy

on:
  # Triggers the workflow on tags
  push:
    branches:
      - "master"

jobs:
  test:
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        python-version: 
        - "2.7"
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8"
        - "3.9"
        # - "3.10"
        module: 
          - "tpm"
          # - "nexus"
          # - "raspberrypi"
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: >-
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: >-
          python -m pip install -r .github/requierments/${{ github.job }}.txt

      - name: Prepare tests
        run: |-
          mkdir -p ${{ runner.temp }}/ansible_collections/
          cp -r ${{ github.workspace }}/ziouf ${{ runner.temp }}/ansible_collections/
        
      - name: Run tests
        run: ansible-test units --python ${{ matrix.python-version }} -vvv
        working-directory: ${{ runner.temp }}/ansible_collections/ziouf/${{ matrix.module }}


  deploy:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: >-
          python -m pip install -r .github/requierments/${{ github.job }}.txt

      - name: Deploy collections
        run: ansible-playbook -i 'localhost,' .github/playbooks/deploy.yml -vvv
        env:
          ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
