
name: Deploy

on:
  # Triggers the workflow on tags
  push:
    branches:
      - "master"

jobs:
  deploy:

    strategy:
      fail-fast: true
      matrix:
        python-version: 
        - 3.6
        - 3.7
        - 3.8
        - 3.9

    runs-on: ubuntu-latest

    env:
      ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
      ANSIBLE_COLLECTIONS_PATH: /home/runner/work/ansible_collections/ansible_collections

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: >-
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: >-
          python -m pip install 
          ansible
          cryptography
          jinja2
          mock
          pytest
          pytest-mock
          pytest-xdist
          pyyaml
          resolvelib
        
      - name: Run tests
        run: |
          for D in ziouf/*/tests/unit; do
            pushd "${D}"
            ansible-test units --python ${{ matrix.python-version }} -vvv
            popd
          done

      - name: Deploy collections
        run: ansible-playbook -i 'localhost,' .github/playbooks/deploy.yml
