
name: Deploy

on:
  # Triggers the workflow on tags
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible
        
      - name: Run tests
        run: |
          for D in ziouf/*; do
            pushd "${D}"
            ansible-test units --venv -v --python 3.9
            popd
          done

      - name: Deploy collections
        run: ansible-playbook -i 'localhost,' .github/playbooks/deploy.yml
